version: '3'

networks:
  proxy:
    external: true

services:
  copycat.mael.tech:
    build: .
    restart: always
    ports:
      - "3000:3000"
      - "3030:3030"
    labels:
      - traefik.backend=copycat
      - traefik.web.frontend.rule=Host:copycat.mael.tech
      - traefik.web.port=3000
      - traefik.sockets.frontend.rule=Host:copycat-ws.mael.tech
      - traefik.sockets.port=3030
    networks:
      - proxy